name: Update Submodules

on:
  schedule:
    - cron: "56 */12 * * *"
  workflow_dispatch:

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure git globally
      run: |
        git config --global user.name "GitHub Submodules Updater"
        git config --global user.email "<>"
        git config --global pull.rebase true
        

    - name: Update git submodules
      run: |
        git submodule update --init --recursive --remote
    
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updated submodules
        commit_user_name: Minigames Updater
        commit_author: Minigames Updater <actions@github.com>
