name: Update Submodules

on:
  schedule:
    - cron: "56 * * * *"

jobs:
  build-version:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update git submodules
      run: |
        git config --global user.name "GitHub Submodules Updater"
        git config --global user.email "<>"
        git config --global pull.rebase true
        git submodule status BomberMan
        git submodule update --init --recursive --remote
        git commit BomberMan -m "Updated submodules"
        git push
